timurmakarov/apps/projects/urls.py
from django.urls import path

from . import views

app_name = 'projects'
urlpatterns = [
	path('', views.index, name = 'index'),
	path('all/', views.all, name = 'all'),
	path('viewsnprojects/', views.viewsnProjects, name = 'viewsnprojects'),
	path('viewhtml5projects/', views.viewhtml5bannersProjects, name = 'viewhtml5projects'),
	path('<int:project_id>/', views.about, name = 'about'),
]



timurmakarov/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	url(r'mdeditor/', include('mdeditor.urls')),
	path('projects/', include('projects.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

timurmakarov/apps/projects/models.py
from django.db import models
from mdeditor.fields import MDTextField

class Project(models.Model):
	project_client = models.CharField('Название компании', max_length = 48)
	project_title = models.CharField('Название проекта', max_length = 36)
	project_type = models.CharField('Тип проекта', max_length = 36)
	project_description = models.TextField('Описание проекта')
	project_body = models.TextField('Тело проекта')
	project_cover = models.ImageField('Обложка проекта', upload_to='upload')
	pub_date = models.DateTimeField('Дата публикации')
	content = MDTextField()

	def __str__(self):
		return self.project_title

	class Meta:
		verbose_name = 'Проект'
		verbose_name_plural = 'Проекты'

class Snippet(models.Model):
	title = models.CharField(max_length = 120)
	body = models.TextField()
	created = models.DateTimeField(auto_now_add = True)

	def __str__(self):
		return self.title

	def body_preview(self):
		return self.body[:50]

timurmakarov/apps/projects/views.py
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render

from .models import Project

def index(request):
	latest_projects_list = Project.objects.order_by('-pub_date')[:3]
	return render(request, 'projects/index.html', {'latest_projects_list': latest_projects_list })

def all(request):
	all_projects_list = Project.objects.order_by('-pub_date')[:15]
	return render(request, 'projects/all.html', {'all_projects_list': all_projects_list })		

def about(request, project_id):	
	try:
		a = Project.objects.get( id = project_id )
	except:
		raise Http404('Проект не найден!')

	return render(request, 'projects/about.html', {'project': a})

def viewsnProjects(request):
	snres = Project.objects.filter(project_type = "Социальные сети")
	return render(request, 'projects/socialnetwork.html', {'snres': snres})

def viewhtml5bannersProjects(request):
	html5res = Project.objects.filter(project_type = "HTML5 баннеры")
	return render(request, 'projects/html5banners.html', {'html5res': html5res})




timurmakarov/apps/projects/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>{% block title %}Мой сайт{% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
	integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	{% load static %}
	<link rel="stylesheet" href="{% static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
	<script src="https://code.jquery.com/jquery-2.2.4.js"></script>
</head>
<body>
	{% block content %}{% endblock %}
</body>
</html>

timurmakarov/apps/projects/templates/nav.html
	<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>{% block title %}Мой сайт{% endblock %}</title>
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
		integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
		{% load static %}
		<link rel="stylesheet" href="{% static 'css/style.css' %}">
		<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
		<script src="https://code.jquery.com/jquery-2.2.4.js"></script>
	</head>
	<body>
		<br>
		<div class="container">

			<div class="row">
				<script>
					$(function () { 
						$('.solo-item__menu a').each(function () {
							var location = window.location.href;
							var link = this.href; 
							if(location == link) {
								$(this).addClass('active');
							}
						});
					});
				</script>
				<div class="col-md-12"><a class="back-btn" href="http://127.0.0.1:8000/projects/">
					<span style="margin-right: 15px">    
						<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
							<path d="M19 12H6M12 5l-7 7 7 7" stroke="#2400FF" stroke-linecap="round"
							stroke-linejoin="round"/>
						</svg></span>На главную</a></div>
						<div class="col-md-1 solo-item__menu"><a href="{% url 'projects:all' %}">Все</a></div>
						<div class="col-md-2 solo-item__menu"><a href="{% url 'projects:viewhtml5projects' %}">HTML5 баннеры</a></div>
						<div class="col-md-2 solo-item__menu"><a href="{% url 'projects:viewsnprojects' %}">Социальные сети</a></div>
						<div class="col-md-2 solo-item__menu"><a href="#">Моушен дизайн</a></div>
						<div class="col-md-1 solo-item__menu"><a href="#">3D</a></div>
						<div class="col-md-1 solo-item__menu"><a href="#">Веб</a></div>
						<div class="col-md-2 solo-item__menu"><a href="#">Диджитал</a></div>
					</div>
				</div>
				{% block content %}
				{% endblock %}
			</body>
			</html>

timurmakarov/apps/projects/templates/projects/about.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="style.css">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
</head>

<body>

	{% extends 'base.html' %}
	{% block content %}

	<div class="container">
		<div class="row">
			<div class="col-md-12"><a class="back-btn" href="http://127.0.0.1:8000/projects/">
				<span style="margin-right: 15px">    
					<svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
						<path d="M19 12H6M12 5l-7 7 7 7" stroke="#2400FF" stroke-linecap="round"
						stroke-linejoin="round"/>
					</svg></span>На главную</a>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="col-md-12">
					<h1><span style="color: #2400FF;">{{project.project_client}}</span>, {{project.project_title}}</h1> 
					<p class="main-page_description">{{project.project_description}}</p>
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
				<div class="col-md-12">
					{{project.project_body}}
				</div>
			</div>
		</div>

		<div class="container">
			<div class="row">
					<div class="col-md-12">{{project.content}}</div>
			</div>
		</div>

		{% endblock %}
	</body>
	</html>


timurmakarov/apps/projects/templates/projects/all.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">

	<title>Я, Тимур Макаров</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Работы</h1>
			</div>
		</div>
	</div>

	{% extends 'nav.html' %}
	{% block content %}
	<div class="container project">
		<div class="row project-item">

			{% if all_projects_list %}
			{% for a in all_projects_list %}
			<div class="col-md-4 solo-item__block" style="padding: 15px;">
				<div class="solo-item" style="background-image: url({{ a.project_cover.url }}); background-size: cover;">
					<div class="solo-item__badge">
						<p>{{ a.project_type }}</p>
					</div>
					<p class="project-card__name">{{ a.project_client }}</p>
					<p>{{ a.project_title }}</p>
					<a class="watch-solo-project__btn" href="{% url 'projects:about' a.id %}"
					style="color: white; display: block; height: 90%; width: 100%"></a>

				</div>

			</div>


			{% endfor %}

		</div>
	</div>

	{% else %}
	Проекты не найдены!
	{% endif %}
	{% endblock %}
</body>
</html>

timurmakarov/apps/projects/templates/projects/html5banners.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
	<title>Я, Тимур Макаров</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Работы</h1>
			</div>
		</div>
	</div>

	{% extends 'nav.html' %}
	{% block content %}

	<div class="container project">
		<div class="row project-item">
			{% if html5res %}
			{% for a in html5res %}
			<div class="col-md-4 solo-item__block" style="padding: 15px;">
				<div class="solo-item" style="background-image: url({{ a.project_cover.url }}); background-size: cover;">
					<div class="solo-item__badge">
						<p>{{ a.project_type }}</p>
					</div>
					<p class="project-card__name">{{ a.project_client }}</p>
					<p>{{ a.project_title }}</p>
					<a class="watch-solo-project__btn" href="{% url 'projects:about' a.id %}"
					style="color: white; display: block; height: 90%; width: 100%"></a>

				</div>

			</div>


			{% endfor %}

		</div>
	</div>


	{% else %}
	Проекты не найдены!
	{% endif %}
	{% endblock %}
</body>
</html>

timurmakarov/apps/projects/templates/projects/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <title>Я, Тимур Макаров</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/1e6d4bcd53.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:200,400,500,600,700,800&display=swap"
    rel="stylesheet">

    <script>
      $(window).on('load', function () {
        $preloader = $('.loaderArea'),
        $loader = $preloader.find('.loader');
        $loader.fadeOut();
        $preloader.delay(350).fadeOut('slow');
    });
</script>

<script type="text/javascript">
    function clock() {
        var d = new Date();
        var month_num = d.getMonth()
        var day = d.getDate();
        var hours = d.getHours();
        var minutes = d.getMinutes();
        var seconds = d.getSeconds();

        month=new Array("января", "февраля", "марта", "апреля", "мая", "июня",
            "июля", "августа", "сентября", "октября", "ноября", "декабря");

        if (day <= 9) day = "0" + day;
        if (hours <= 9) hours = "0" + hours;
        if (minutes <= 9) minutes = "0" + minutes;
        if (seconds <= 9) seconds = "0" + seconds;

        date_time = "Сегодня - " + day + " " + month[month_num] + " " + d.getFullYear() +
        " г.&nbsp;&nbsp;&nbsp;Текущее время - "+ hours + ":" + minutes + ":" + seconds;
        if (document.layers) {
         document.layers.doc_time.document.write(date_time);
         document.layers.doc_time.document.close();
     }
     else document.getElementById("doc_time").innerHTML = date_time;
     setTimeout("clock()", 1000);
 }
</script>

</head>
<body>
   <div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1><span style="color: #2400FF;">Я</span>, Тимур Макаров<span><img style="width: 5%; margin-left: 10px" src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/232/waving-hand-sign_1f44b.png"></span></h1>
            <p class="main-page_description">веб, моушен, диджитал, 3D, HTML5, CSS</p>
        </div>
    </div>
</div>

<div class="container project">
    <h2>Последние работы<span><img style="width: 2%; margin-left: 5px" src="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/120/apple/232/fire_1f525.png"></span></h2>
    <div class="row project-item">
        {% extends 'base.html' %}
        {% load static %}
        {% block title %} Последние работы {% endblock %}
        {% block content %}
        {% if latest_projects_list %}
        {% for a in latest_projects_list %}

        <div class="col-md-4 solo-item__block" style="padding: 15px;">
            <div class="solo-item" style="background-image: url({{ a.project_cover.url }}); background-size: cover;">
                <div class="solo-item__badge">
                    <p>{{ a.project_type }}</p>
                </div>
                <p class="project-card__name">{{ a.project_client }}</p>
                <p>{{ a.project_title }}</p>
                <a class="watch-solo-project__btn" href="{% url 'projects:about' a.id %}"
                style="color: white; display: block; height: 90%; width: 100%"></a>

            </div>

        </div>


        {% endfor %}

    </div>



    <a href="{% url 'projects:all' %}">Смотреть все
        <span style="margin-left: 15px"><svg width="24" height="24" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg">
            <path d="M12 5L19 12L12 19M5 12H18H5Z" stroke="#2400FF" stroke-linecap="round"
            stroke-linejoin="round"/>
        </span>
    </svg>
</a>
</div>

<div class="container сontacts-parrent">
    <h2>Контакты</h2>
    <div class="row contacts">

        <div class="col-md-4">
            <i class="fas fa-phone-square-alt"></i>
            <a href="tel:89872895075">+79872895075</a>
        </div>

        <div class="col-md-4">
            <i class="fas fa-envelope"></i>
            <a href="mailto:hi@timurmakarov.ru">hi@timurmakarov.ru</a>
        </div>

        <div class="col-md-4">
            <i class="fab fa-telegram-plane"></i>
            <a href="https://teleg.one/timurmakarov">@timurmakarov</a>
        </div>

    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-12">
            <p class="footer-desc">
               Дизайн сайта на Figma, вёрстка на Bootstrap, бэкенд на Python Django  
           </p>
       </div>
       <div class="col-md-12 date-time">
           <span id="doc_time">
               Дата и время
           </span>
           <script type="text/javascript">
             clock();
         </script>
     </div>
 </div>
</div>


{% else %}
Проекты не найдены!
{% endif %}


<img src="">

{% endblock %}
</body>
</html>

timurmakarov/apps/projects/templates/projects/socialnetwork.html
<!DOCTYPE html>
<html lang="ru">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width">
	<title>Я, Тимур Макаров</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,600,700,800&display=swap" rel="stylesheet">
</head>
<body>
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<h1>Работы</h1>
			</div>
		</div>
	</div>

	{% extends 'nav.html' %}
	{% block content %}

	<div class="container project">
		<div class="row project-item">

			{% if snres %}
			{% for a in snres %}
			<div class="col-md-4 solo-item__block" style="padding: 15px;">
				<div class="solo-item" style="background-image: url({{ a.project_cover.url }}); background-size: cover;">
					<div class="solo-item__badge">
						<p>{{ a.project_type }}</p>
					</div>
					<p class="project-card__name">{{ a.project_client }}</p>
					<p>{{ a.project_title }}</p>
					<a class="watch-solo-project__btn" href="{% url 'projects:about' a.id %}"
					style="color: white; display: block; height: 90%; width: 100%"></a>

				</div>

			</div>
			{% endfor %}

		</div>
	</div>


	{% else %}
	Проекты не найдены!
	{% endif %}
	{% endblock %}
</body>
</html>